name: thirtydegre.es
favicon: null
layout_spectrum: 0.9950091927312315
typography_spectrum: 0.4441830888390541
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8927565591875464
  lightness: 0.7542660757899284
  saturation: 0.06489443010650575
  rhythmicContrast: 0.5602320635225624
purpose: []
